### ISSUE TITLE
Does not support dynamic (lazy) import() function

### ISSUE THREAD

**Issue by ymhr** [vuedoc/parser#25]
I've been trying to document my components, but when I run I often get this error:
`Unexpected token import`

I thought perhaps it did not support es6 importing, but after testing directly with a component, I was able to determine that it's `import(...)` statements that it cannot parse, i.e. webpack codesplitting.

Is there a solution for this?

**Comment by demsking** [comment]
Could you provide a sample of the failed component please?

**Comment by ymhr** [comment]
Any component using a dynamic import will fail, e.g.
```vue
<template>
  <div>
    <Lazy />
  </div>
</template
<script>
  export default {
    components: {
      Lazy: import('./components/Lazy.vue')
    }
  }
</script>
```

I have done some reading since I made this issue, and I think the issue is that espree does not support dynamic imports, and they have no plans to until it reaches stage-4 https://github.com/eslint/espree/issues/344 . An alternative would be switching to something like esprima or acorn, both of which have plugins to support dynamic imports, although I am not sure how much work that would entail.

**Comment by demsking** [comment]
I'll fix this by escaping the `import` keyword

**Comment by demsking** [comment]
Fixed. It'll be released soon

**Comment by demsking** [comment]
**This project has been moved to https://gitlab.com/vuedoc/parser**
